version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - python3-poetry
  jobs:
    post_create_environment:
      - poetry export --only docs -o requirements.txt

python:
  install:
    - path: .
    - requirements: requirements.txt
