version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 -
      - ~/.local/share/pypoetry/venv/bin/poetry config virtualenvs.create false
      - ~/.local/share/pypoetry/venv/bin/poetry install --with docs --without flake8,test

sphinx:
  configuration: docs/conf.py
