version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - poetry export --with docs --without flake8,test --format=requirements.txt --output=requirements.txt

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/source/conf.py
