---
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry export --only main,docs -o requirements.txt
      - poetry run python -m tools.build_theme_color_doc

python:
  install:
    - path: .
    - requirements: requirements.txt
