name: theme resources checker
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install python dependencies
      run: pip install . pyside6 click

    - name: Check resources
      run: python .github/scripts/check_theme_dist.py
