name: theme resources checker
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install python dependencies
      run: pip install . pyside6 rich

    - name: Check resources
      run: python -m tools.build_resources --check
