name: linter
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: markdown yaml py-type
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2

    - name: Lint python type
      uses: pre-commit/action@v2.0.3
      with:
        extra_args: pyright

    - name: Lint yaml and markdown
      uses: github/super-linter/slim@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_YAML: true
        VALIDATE_MARKDOWN: true
