name: linter
on:
  push:
    branches:
      - main
    # Remove the line above to run when pushing to master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_JSON: true
        VALIDATE_MARKDOWN: true
