name: Automatically update svg

on:
  schedule:
    - cron: '23 1 * * *' # Runs at 01:23 UTC every day
  workflow_dispatch:
    inputs:
      dry:
        description: Dry Run
        default: '1'

env:
  BRANCH_NAME: 'auto-update-svg'
  COMMIT_MESSAGE: 'Update svg of material design icons'
  PR_TITLE: 'Automatic update svg for material design icons'

jobs:
  update-svg-of-material-design-icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: git-actions/set-user@v1
      - uses: snok/install-poetry@v1
      - run: poetry install --only main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check branch
        id: branch
        run: |
          status=0
          git rev-parse --verify ${{ env.BRANCH_NAME }} || status=$?
          echo $status
          echo exists=$($status) >> $GITHUB_OUTPUT
      - if: steps.branch.outputs.exists != '0'
        run: git branch ${{ env.BRANCH_NAME }}
      - run: git switch ${{ env.BRANCH_NAME }}
      - name: Download svg of material design icons and update resources
        run: |
          poetry run python tools/download_material_icons.py
          poetry run python -m tools.build_resources
      - name: Check diff
        id: diff
        run: |
          git add -N .  # Include new files
          echo count=$(git diff --name-only | wc -l) >> $GITHUB_OUTPUT
      - if: steps.diff.outputs.count != 0
        run: git commit -am "${{ env.COMMIT_MESSAGE }}"
      - name: Push changes
        if: steps.diff.outputs.count > 0 && github.event.inputs.dry != '1'
        run: git push -u origin ${{ env.BRANCH_NAME }}
      - name: Create PR
        if: steps.diff.outputs.count > 0 && steps.branch.outputs.exists != '0' && github.event.inputs.dry != '1'
        run: |
          gh pr create \
          -t "${{ env.PR_TITLE }}" \
          -b 'Update svg of material design icons'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
